#!/usr/bin/sh

# If refreshing bspwm, remove all previous rules
bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

sxhkd &

# Run polybar
~/.config/polybar/launch.sh &

bspc config border_width         3
bspc config window_gap          15
bspc config top_padding         24    # equals to polybar height

bspc config split_ratio          0.52
# bspc config borderless_monocle   true
# bspc config gapless_monocle      true

bspc rule -a Pavucontrol state=floating
bspc rule -a Zathura state=tiled
bspc rule -a alsamixer state=floating


# Should run on x profile
dunst &
touchpad.sh &
xset r rate 300 50 &
nm-applet &
picom -f &
setkb &
feh --bg-scale ~/Pictures/bg.png &
unclutter &

# no swallow
pgrep bspswallow || bspswallow &

wmname LG3D &
