#!/bin/bash

BRIGHT=$(xrandr --verbose | grep -i brightness | cut -f2 -d ' ' | head -n1)
MON=$(xrandr | grep " connected" | cut -f1 -d " ")

if [ $1 != "inc" -a $1 != "dec" ]
then
  echo "$1: command not found"
  exit 1
fi

if [ $(echo "if ($2 > 1 || $2 < 0) 1 else 0" | bc) -eq 1 ]
then
  echo "Please enter a value from 0 to 1"
  exit 1
fi

if [ $1 == "inc" ]
then
  NEW=$(echo "$BRIGHT + $2" | bc)
  if [ $(echo "if ($NEW > 1) 1 else 0" | bc) -eq 1 ]
  then
    xrandr --output $MON --brightness 1
  else
    xrandr --output $MON --brightness $NEW
  fi
fi

if [ $1 == "dec" ]
then
  NEW=$(echo "$BRIGHT - $2" | bc)
  if [ $(echo "if ($NEW < 0.2) 1 else 0" | bc) -eq 1 ]
  then
    xrandr --output $MON --brightness 0.2
  else
    xrandr --output $MON --brightness $NEW
  fi
fi

